default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>


development:
  <<: *default
  database: task_manager_development
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

test:
  <<: *default
  database: task_manager_test


production:
  <<: *default
  database: task_manager_production
  username: task_manager
  password: <%= ENV["TASK_MANAGER_DATABASE_PASSWORD"] %>
